### PR TITLE
Use moment.locale when available

### LINKED ISSUE #11: `moment.lang` deprecated
As of moment@2.8.1 `moment.lang` is deprecated and was replaced by `moment.locale`. http://momentjs.com/docs/#/i18n/changing-locale/

As one may provide their own instance of moment this may cause issues.

There are two possible ways to fix this:
1. Bump the moment dependency from ~2.0.0 to ^2.8.1 and use `moment.locale`
2. 

``` js
var locale = typeof moment.locale === 'function' ? 'locale' : 'lang'
// …
moment[locale]('en')
```

Changing ~2.0.0 to ^2.0.0 would still be recommended though.

What do you think? Not so sure, but I think I prefer 2.

### PR DESCRIPTION
**Pull request by boennemann**
fixes #11

also #12 

@davidpfahler

### CODE REVIEW

**Comment by boennemann** [comment]
So there are few issues left:
1. With higher versions of moment non iso-strings are deprecated as well, which could be in the library user's responsibility, but needs to be documented. See https://github.com/moment/moment/issues/1407
2. The example has outdated dependencies and doesn't seem to work even on master, as https://github.com/ehd/ng-time-relative/blob/master/index.js#L68 is executed every single time and dates are all shown absolute.

**Comment by davidpfahler** [comment]
@boennemann Re point 2: The dates all being rendered as absolute values seems to have been a [conscious decision](https://github.com/ehd/ng-time-relative/commit/e0c0ac7cb6ac01a33affb65824f8e1ac33508dd8#diff-168726dbe96b3ce427e7fedce31bb0bcL36).

**Comment by seidtgeist** [comment]
Maybe the "render dates before/after today as calendar date" behaviour should be configurable, and the default should be to not render the calendar date?

**Comment by davidpfahler** [comment]
@ehd I think what @boennemann meant by "examples don't work" is that the [README.md](https://github.com/ehd/ng-time-relative/blob/master/README.md#dom-output-examples) says that the behavior to print relative time diffs while the actual output of the examples renders as calendar date.

**Comment by seidtgeist** [comment]
final_5de8d1396280800014aac5a4_21729

**Pull request closed without merging**
