### PR TITLE
fix: correctly check for provided dependencies

### PR DESCRIPTION
**Pull request by boennemann**
My current setup inside `browserify` looks like this:

``` js
var angular = require('angular')
var ngTimeRelative = require('ng-time-relative')
var moment = require('ng-time-relative/node_modules/moment')

var app = angular.module('woop', [])
app.constant('moment', moment)
ngTimeRelative(app)
```

This way in the browser `if (moment) {`(line 30) fails with "Uncaught ReferenceError: moment is not defined ".

Correctly checking for the undefinedness of the provided modules fixes that.

### CODE REVIEW

**Comment by seidtgeist** [comment]
LGTM

**Comment by seidtgeist** [comment]
Thanks!

**Comment by boennemann** [comment]
:tada:

**Comment by seidtgeist** [comment]
Btw, I released 0.6.0. Just for you. I should get rid of those files in `dist` though.

**Comment by boennemann** [comment]
[Thanks](https://github.com/conc-at/twitterwall/commit/f43ae4a2286f9582c3533d4b130aa1e63b225371).

If you mean getting rid of dist files in the repo I'd suggest changing the package.json like this:

``` diff
"scripts": {
-  "install": "make build"
+  "publish": "make build"
}
```

Add `dist` to the `.gitignore` and create `.npmignore` w/o the dist entry and you are good to go :+1:

**Comment by seidtgeist** [comment]
I'd love to get rid of the distfiles altogether and force people to use browserify or something. What would you suggest?

**Comment by boennemann** [comment]
Not sure If I'd purposely break things for people, but would be nice to release 1.0.0 anyways ;)

Getting rid of dist in the repo would still be a great start though.

**Comment by seidtgeist** [comment]
@boennemann I actually think your approach makes most sense. We generate dist files on the client, so if npm installs the package the dist file is there and can be included via script tag just as before.

**Comment by boennemann** [comment]
@ehd I can't find the resource right now, but generating things on the client is actually discouraged. Is there a reason why a prepublish hook can't be used? Because then the generated files will just be added to the tarball and we're good to go.

I could send you a PR.

**Comment by seidtgeist** [comment]
Sorry, yes, that makes more sense. Among other things it's easy to generate invalid artifacts on the client unless you're careful. PR would be very welcome :heart:

**Pull request merged**
